## Numpy : Package for Multi-dimensional array
### Matrix(1d)
### Matrix(2d or 1d)
### Create an array

In [1]:
import numpy as np

In [2]:
simple_list=[1,2,3]
np.array(simple_list)

array([1, 2, 3])

In [3]:
arr=np.array(simple_list)
arr

array([1, 2, 3])

In [4]:
list_of_lists=[[1,2,3],[4,4,4],[5,5,5]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [5]:
np.arange(13,45)

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
       30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [7]:
np.arange(13,61,4)

array([13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57])

In [8]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(8,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [20]:
np.eye(5,dtype=int)### Identity Matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [34]:
np.random.rand(2,13)

array([[0.5685215 , 0.07320765, 0.7170476 , 0.27546217, 0.90515414,
        0.73120226, 0.93618831, 0.30409959, 0.12050141, 0.65145729,
        0.50532128, 0.68717402, 0.05182075],
       [0.72800793, 0.54074949, 0.25176833, 0.509471  , 0.45081653,
        0.29718647, 0.72981205, 0.17970982, 0.19698759, 0.67995806,
        0.24503676, 0.36853612, 0.31507158]])

In [33]:
np.random.randn(2,6)

array([[-1.44498318,  1.2805858 , -0.27860117,  0.50610221, -1.16586921,
        -1.7586553 ],
       [ 1.72170907, -0.09736393, -0.14292485,  1.16741858,  0.00487757,
         0.78186855]])

In [30]:
np.random.randint(0,10,100)

array([5, 3, 1, 3, 7, 3, 5, 4, 0, 8, 0, 4, 4, 4, 2, 1, 0, 4, 9, 4, 0, 0,
       1, 6, 0, 9, 4, 2, 1, 5, 8, 6, 8, 4, 0, 6, 3, 9, 6, 9, 3, 1, 1, 8,
       6, 2, 6, 9, 9, 4, 9, 9, 8, 1, 1, 8, 4, 2, 6, 2, 7, 0, 8, 3, 3, 9,
       0, 1, 4, 2, 5, 2, 2, 7, 8, 7, 6, 1, 9, 4, 0, 9, 7, 8, 6, 8, 8, 1,
       6, 1, 7, 3, 9, 2, 9, 3, 8, 3, 4, 6])

In [26]:
np.random.randint(10,100,20)

array([97, 61, 23, 31, 94, 56, 69, 74, 74, 64, 71, 32, 47, 65, 59, 16, 88,
       12, 71, 92])

In [35]:
np.random.randint(25,100,20)

array([68, 64, 79, 91, 69, 51, 28, 77, 56, 28, 56, 73, 44, 62, 26, 98, 76,
       78, 71, 77])

In [36]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
sample_array=np.arange(3,30)
arr=sample_array
arr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [39]:
rand_array=np.random.randint(0,10,15)
rand_array

array([2, 7, 8, 6, 5, 8, 4, 7, 4, 5, 9, 7, 3, 6, 6])

In [43]:
rand_array.min()

2

In [44]:
rand_array.max()

9

In [45]:
rand_array.argmin()

0

In [46]:
rand_array.max()

9

In [48]:
rand_array.dtype

dtype('int32')

In [50]:
b=np.eye(7)
b

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [52]:
c=a.T
c

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [53]:
b=np.random.rand(3,4)
b

array([[0.58466704, 0.7886607 , 0.73888777, 0.45035483],
       [0.96675001, 0.22394719, 0.91237912, 0.28303529],
       [0.81408716, 0.16694741, 0.20773547, 0.69176379]])

In [55]:

c=b.T
c

array([[0.58466704, 0.96675001, 0.81408716],
       [0.7886607 , 0.22394719, 0.16694741],
       [0.73888777, 0.91237912, 0.20773547],
       [0.45035483, 0.28303529, 0.69176379]])

In [61]:
sample_array=np.arange(10,28)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [67]:
sample_array=sample_array.reshape(6,3)
sample_array

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [69]:
sample_array[5]=100
sample_array

array([[ 10,  11,  12],
       [ 13,  14,  15],
       [ 16,  17,  18],
       [ 19,  20,  21],
       [ 22,  23,  24],
       [100, 100, 100]])

In [74]:
sample_array=np.arange(10,100)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [76]:
sample_array[1:12]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [77]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [78]:
sample_array[:]=1001
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001])

In [79]:
sample_matrix=np.array([[13,45,6,9],[3,13,24,7],[34,54,6,7]])
sample_matrix

array([[13, 45,  6,  9],
       [ 3, 13, 24,  7],
       [34, 54,  6,  7]])

In [82]:
sample_matrix[1,3]

7

In [87]:
sample_matrix[1][1]

13

In [88]:
sample_matrix[:,1]

array([45, 13, 54])

In [90]:
sample_matrix[:,3]

array([9, 7, 7])

In [91]:
sample_matrix[1:2,1:3]

array([[13, 24]])

In [92]:
sample_matrix[1:2,2:3]

array([[24]])

In [93]:
sample_matrix[2]

array([34, 54,  6,  7])

In [95]:
sample_array=np.arange(1,41)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [96]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80])

In [97]:
sample_array-sample_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [99]:
sample_array*sample_array

array([   1,    4,    9,   16,   25,   36,   49,   64,   81,  100,  121,
        144,  169,  196,  225,  256,  289,  324,  361,  400,  441,  484,
        529,  576,  625,  676,  729,  784,  841,  900,  961, 1024, 1089,
       1156, 1225, 1296, 1369, 1444, 1521, 1600])

In [100]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13, 2.90488497e+13, 7.89629602e+13,
       2.14643580e+14, 5.83461743e+14, 1.58601345e+15, 4.31123155e+15,
       1.17191424e+16, 3.18559318e+16, 8.65934004e+16, 2.35385267e+17])

In [101]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558,
       5.56776436, 5.65685425, 5.74456265, 5.83095189, 5.91607978,
       6.        , 6.08276253, 6.164414  , 6.244998  , 6.32455532])

In [102]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738,
       3.4339872 , 3.4657359 , 3.49650756, 3.52636052, 3.55534806,
       3.58351894, 3.61091791, 3.63758616, 3.66356165, 3.68887945])

In [103]:
np.max(sample_array)

40

In [104]:
np.min(sample_array)

1

In [106]:
np.argmax(sample_array)

39

In [107]:
np.argmin(sample_array)

0

In [108]:
np.square(sample_array)

array([   1,    4,    9,   16,   25,   36,   49,   64,   81,  100,  121,
        144,  169,  196,  225,  256,  289,  324,  361,  400,  441,  484,
        529,  576,  625,  676,  729,  784,  841,  900,  961, 1024, 1089,
       1156, 1225, 1296, 1369, 1444, 1521, 1600], dtype=int32)

In [109]:
np.std(sample_array)

11.543396380615196

In [110]:
np.var(sample_array)

133.25

In [111]:
np.mean(sample_array)

20.5

In [113]:
array=np.random.randn(3,4)
array

array([[-0.91471138, -0.24643986,  0.76691621,  0.06997322],
       [-1.13081611,  0.9106969 , -0.42019184, -0.62578686],
       [ 0.00662518, -0.40554636,  1.2809561 , -0.04988656]])

In [114]:
np.round(array,decimals=4)

array([[-0.9147, -0.2464,  0.7669,  0.07  ],
       [-1.1308,  0.9107, -0.4202, -0.6258],
       [ 0.0066, -0.4055,  1.281 , -0.0499]])

In [116]:
sports=np.array(['golf','cricket','fball','cricket','basketball'])
np.unique(sports)

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')

In [117]:
np.random.randint([1,5,7],10)

array([6, 8, 8])

### Pandas

In [118]:
import pandas as pd

In [119]:
labels=['a','b','c','d']

In [120]:
list=[14,15,25,27]

In [121]:
import numpy as np

In [123]:
array==np.array([1,2,3,4])

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [125]:
dict={'x':11,'y':12,'z':13,'a':14}

In [126]:
pd.Series(list)

0    14
1    15
2    25
3    27
dtype: int64

In [127]:
pd.Series(list,index=labels)

a    14
b    15
c    25
d    27
dtype: int64

In [128]:
pd.Series(list,labels)

a    14
b    15
c    25
d    27
dtype: int64

In [129]:
pd.Series(dict)

x    11
y    12
z    13
a    14
dtype: int64

### Pandas dataframe and indexing

In [131]:
games1=pd.Series([12,13,11,14],index=['tennis','koko','tug-offwar','chess'])
games1

tennis        12
koko          13
tug-offwar    11
chess         14
dtype: int64

In [132]:
games2=pd.Series([10,9,8,4],index=['baseball','koko','shuttle','chess'])
games2

baseball    10
koko         9
shuttle      8
chess        4
dtype: int64

In [133]:
games1+games2

baseball       NaN
chess         18.0
koko          22.0
shuttle        NaN
tennis         NaN
tug-offwar     NaN
dtype: float64

In [134]:
games1['koko']

13

In [141]:
df2=pd.DataFrame(np.random.rand(7,6), index='S T U V W X Z'.split(),columns='Marks1 Marks2 Marks3 Marks4 Marks5 Marks6'.split())
df2

Marks1    Marks2    Marks3    Marks4    Marks5    Marks6
S  0.284470  0.303148  0.989752  0.596853  0.767205  0.370392
T  0.151064  0.839734  0.121919  0.701933  0.066149  0.057020
U  0.931705  0.188220  0.387123  0.038376  0.426931  0.807213
V  0.557856  0.378028  0.183947  0.921953  0.649143  0.766792
W  0.115771  0.932916  0.338003  0.145186  0.799605  0.136125
X  0.227170  0.390526  0.586545  0.760962  0.912021  0.326860
Z  0.069211  0.213768  0.942459  0.730927  0.708045  0.566174

In [144]:
df2['Marks3']

S    0.989752
T    0.121919
U    0.387123
V    0.183947
W    0.338003
X    0.586545
Z    0.942459
Name: Marks3, dtype: float64

In [146]:
df2[['Marks3','Marks2','Marks4']]

Marks3    Marks2    Marks4
S  0.989752  0.303148  0.596853
T  0.121919  0.839734  0.701933
U  0.387123  0.188220  0.038376
V  0.183947  0.378028  0.921953
W  0.338003  0.932916  0.145186
X  0.586545  0.390526  0.760962
Z  0.942459  0.213768  0.730927

In [150]:
df2['Marks7']= df2['Marks2']+df2['Marks4']


In [151]:
df2.drop('Marks6',axis=1)

Marks1    Marks2    Marks3    Marks4    Marks5    Marks7
S  0.284470  0.303148  0.989752  0.596853  0.767205  0.900001
T  0.151064  0.839734  0.121919  0.701933  0.066149  1.541667
U  0.931705  0.188220  0.387123  0.038376  0.426931  0.226596
V  0.557856  0.378028  0.183947  0.921953  0.649143  1.299980
W  0.115771  0.932916  0.338003  0.145186  0.799605  1.078102
X  0.227170  0.390526  0.586545  0.760962  0.912021  1.151488
Z  0.069211  0.213768  0.942459  0.730927  0.708045  0.944696

In [152]:
df2.drop('U')

Marks1    Marks2    Marks3    Marks4    Marks5    Marks6    Marks7
S  0.284470  0.303148  0.989752  0.596853  0.767205  0.370392  0.900001
T  0.151064  0.839734  0.121919  0.701933  0.066149  0.057020  1.541667
V  0.557856  0.378028  0.183947  0.921953  0.649143  0.766792  1.299980
W  0.115771  0.932916  0.338003  0.145186  0.799605  0.136125  1.078102
X  0.227170  0.390526  0.586545  0.760962  0.912021  0.326860  1.151488
Z  0.069211  0.213768  0.942459  0.730927  0.708045  0.566174  0.944696

In [153]:
df3={'ID':[201,202,203,204], 'Name':['Neptune','Mercury','Pluto','Mars'], 'Profit':[21,31,41,51]}
df=pd.DataFrame(df3)
df

ID     Name  Profit
0  201  Neptune      21
1  202  Mercury      31
2  203    Pluto      41
3  204     Mars      51

In [154]:
df.drop(3)

ID     Name  Profit
0  201  Neptune      21
1  202  Mercury      31
2  203    Pluto      41

In [155]:
df['Name']

0    Neptune
1    Mercury
2      Pluto
3       Mars
Name: Name, dtype: object

In [157]:
df[['Name','ID']]

Name   ID
0  Neptune  201
1  Mercury  202
2    Pluto  203
3     Mars  204

In [171]:
df=pd.read_csv("plantgrowth.csv")
df


sr  weight group
0    1    4.17  ctrl
1    2    5.58  ctrl
2    3    5.18  ctrl
3    4    6.11  ctrl
4    5    4.50  ctrl
5    6    4.61  ctrl
6    7    5.17  ctrl
7    8    4.53  ctrl
8    9    5.33  ctrl
9   10    5.14  ctrl
10  11    4.81  trt1
11  12    4.17  trt1
12  13    4.41  trt1
13  14    3.59  trt1
14  15    5.87  trt1
15  16    3.83  trt1
16  17    6.03  trt1
17  18    4.89  trt1
18  19    4.32  trt1
19  20    4.69  trt1
20  21    6.31  trt2
21  22    5.12  trt2
22  23    5.54  trt2
23  24    5.50  trt2
24  25    5.37  trt2
25  26    5.29  trt2
26  27    4.92  trt2
27  28    6.15  trt2
28  29    5.80  trt2
29  30    5.26  trt2